include:
  - https://gitlab.com/wondermonger/ci-tools/raw/v6.0.3/tpl/node/base.yml
  - https://gitlab.com/wondermonger/ci-tools/raw/v6.0.3/tpl/node/post-install/lint.yml
  - https://gitlab.com/wondermonger/ci-tools/raw/v6.0.3/tpl/node/test/expanded.yml
  - https://gitlab.com/wondermonger/ci-tools/raw/v6.0.3/tpl/node/test/coverage.yml
  - https://gitlab.com/wondermonger/ci-tools/raw/v6.0.3/tpl/node/post-build/pages.yml

documentation:
  except:
    - tags
  artifacts:
    paths:
      - docs/
  script: npm run build:docs
  stage: build

release:
  only:
    - master
  script:
    - ci-git-config
    - ci-git-release -a docs
  stage: deploy
