image: wondermonger/ci-tools:latest

stages:
  - install
  - build
  - test
  - deploy

install:
  artifacts:
    paths:
      - node_modules/
  script: ci-node-install
  stage: install

build:
  artifacts:
    paths:
      - docs/rules/
  script: ci-node-build
  stage: build

lint:
  script: ci-node-lint
  stage: test

unit:
  script: ci-node-unit-tests
  stage: test

integration:
  script: ci-node-integration-tests
  stage: test

release:
  only:
    - master
  script:
    - ci-git-config
    - ci-git-node-release
  stage: deploy

publish:
  only:
    - tags
  script: ci-node-publish
  stage: deploy
