image: wondermonger/ci-tools:v2

stages:
  - install
  - lint
  - build
  - test
  - deploy

install:
  artifacts:
    paths:
      - node_modules/
  script: ci-node-install
  stage: install

outdated:
  allow_failure: true
  script: ci-node-outdated
  stage: install

lint:
  script: ci-node-lint
  stage: lint

documentation:
  only:
    - master
  artifacts:
    paths:
      - docs/
  script: ci-node-build docs
  stage: build

unit:
  script: ci-node-test unit
  stage: test

integration:
  script: ci-node-test integration
  stage: test

release:
  only:
    - master
  script:
    - ci-git-config
    - ci-git-release -a docs
  stage: deploy

publish:
  only:
    - tags
  script:
    - ci-node-config
    - ci-node-release
  stage: deploy
